### ISSUE TITLE
执行main.py后check_stock报错

### ISSUE THREAD

**Issue by rellimshu** [jozhn/ddmc.monitor#15]
执行main.py后check_stock报错:
Traceback (most recent call last):

  File "D:\1\main.py", line 94, in <module>

    run()

  File "D:\1\main.py", line 84, in run

    check_stock()

  File "D:\1\check_stock.py", line 117, in check_stock

    if len(menu['products']) > 0:

TypeError: 'NoneType' object is not subscriptable

**Comment by IMLR** [comment]
因为405了，现在要抓包带登录信息才能访问
